name: STEAMBOAT
favicon: null
layout_spectrum: 0.8088520611636341
typography_spectrum: 0.41979247494600713
title: S.T.E.A.M. BOAT
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9378818261902779
  lightness: 0.875
  saturation: 0.6077104539144784
  rhythmicContrast: 0.80106554296799
purpose: []
